name: Caller Workflow
on: workflow_dispatch
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-wf.yml
    with:
      target_env: production
    secrets:
      API_TOKEN: "token-passed-by-caller-wf"