name: container-wf
on: workflow_dispatch
jobs:
  job_1:
    runs-on: ubuntu-latest
    container:
      image: node:18-bullseye # The job runs inside this container
      env:
        NODE_ENV: production
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   
      - name: Display Node.js version
        run: node --version
      - name: Display NODE_ENV variable
        run: echo "NODE_ENV is $NODE_ENV"