name: outputs-exposure
on: workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            example_output: ${{steps.step1.outputs.Name}}
        steps:
            - name: send output-value
              id: step1
              run: echo "Name=Akash" >> $GITHUB_OUTPUT

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: get output-value
              run: echo "the name is ${{needs.job1.outputs.example_output.Name}}"